POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Testi tyyppi"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "Testi tyyppi"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Testi tyyppi",
  "number": "040-11223344"
}
